### PR TITLE
Add extra validation for option mode, close #6

### LINKED ISSUE #6: Undefined $option['mode'] error
I got errors on frontend debug mode

```log
Notice: Undefined index: mode in /var/www/html/wp-content/plugins/csp-manager/src/CSP_Manager/Core.php on line 54 Notice: Undefined index: mode in /var/www/html/wp-content/plugins/csp-manager/src/CSP_Manager/Core.php on line 57 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/csp-manager/src/CSP_Manager/Core.php:54) in /var/www/html/wp-content/plugins/csp-manager/src/CSP_Manager/Core.php on line 74 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-content/plugins/csp-manager/src/CSP_Manager/Core.php:54) in /var/www/html/wp-content/plugins/headers-security-advanced-hsts-wp/headers-security-advanced-hsts-wp.php on line 79
```

Issue related to this line code https://github.com/16patsle/wordpress-csp-manager/blob/07590b478c8b1785673466b38a7db64f692d42d4/src/CSP_Manager/Core.php#L54

### PR DESCRIPTION
**Pull request by reatlat**

### CODE REVIEW

**Comment by reatlat** [comment]
@16patsle Will you please review and merge it? Some of my projects use your plugin with my hotfix, but wordfence highlight plugin as modified. And probably infected 😂

**Comment by 16patsle** [comment]
Oh, sorry. Apparently I didn't see this. I'll try looking through it this week, and hopefully merge and release it too. Thank you!

**Comment by 16patsle** [comment]
Should be out now!

**Comment by reatlat** [comment]
> Should be out now!

TY sir!

**Pull request merged**
